image: Visual Studio 2015

version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore -Verbosity quiet

build:
  parallel: true
  project: src/VsixLogger.csproj
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  verbosity: quiet
  configuration: Release

after_build:
  - ps: nuget pack src\VsixLogger.csproj

deploy:
  - provider: NuGet
    artifact: /.*\.nupkg/
    api_key:
      secure: 6xBu/05BWJDPa2PRkxEH3PHU/caLvy2lzf1eWdRBGXwSCTejHtI+6e0V4s2LaVri
    on:
      branch: master
      appveyor_repo_commit_message_extended: /\[release\]/