image: Visual Studio 2015

build_script:
  - nuget restore -Verbosity quiet

after_test:
  - ps: nuget pack src\VsixLogger.csproj
  - ps: Vsix-PushArtifacts

artifacts:
  - path: src\**\*.nupkg
    name: NuGet package

deploy:
  - provider: NuGet
    artifact: /NuGet/
    api_key:
      secure: 6xBu/05BWJDPa2PRkxEH3PHU/caLvy2lzf1eWdRBGXwSCTejHtI+6e0V4s2LaVri
    on:
      branch: master
      appveyor_repo_commit_message_extended: /\[release\]/